version: '3.8'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
      - ./dockerConfigs/influxdb-data:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=exampledb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminadmin
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=user123
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
      - ./dockerConfigs/mosquitto:/mosquitto
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      - ./dockerConfigs/nodeRed-data:/data
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana-data:/var/lib/grafana
      - ./dockerConfigs/grafana-dashboards:/var/lib/grafana/dashboards
volumes:
  influxdb-data:
  mosquitto-data:
  mosquitto-log:
  grafana-data:

